### ISSUE TITLE
exception when notifier not exist

### ISSUE THREAD

**Issue by Castill** [kaddopur/twse#14]
In **twse-cli - migration.js**, the `notifiers` would be `undefined` when `notifier` not exist and lead to `Object.entries(notifiers)` throw exception.

```js
const { notifier = {}, notifier: { notifiers } = {} } = state;
```

### Error Log

```log
  var newNotifiers = Object.entries(notifiers).reduce(function (acc, _ref) {
                            ^

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at migrateConditonAddValueField (/usr/local/lib/node_modules/twse-cli/dist/migrations.js:19:29)
    at /usr/local/lib/node_modules/twse-cli/dist/migrations.js:52:12
    at Array.reduce (<anonymous>)
    at exports.default (/usr/local/lib/node_modules/twse-cli/dist/migrations.js:51:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/twse-cli/dist/store.js:32:45)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
```

**Comment by kaddopur** [comment]
@Castill thx for the issue. Fixed and released in v1.6.2
